const { Regex } = require('@companion-module/base')

module.exports = {
        getConfigFields() {
                return [
                        {
                                type: 'static-text',
                                id: 'info',
                                width: 12,
                                label: 'Information',
                                value:
                                        'This module listens to incoming TSL UMD data at the TCP or UDP port specified and updates Feedbacks and Variables accordingly.',
                        },
                        {
                                type: 'number',
                                id: 'port',
                                width: 6,
                                label: 'Listening Port',
                                default: '9800',
                                regex: this.REGEX_PORT,
                        },
                        {
                                type: 'dropdown',
                                id: 'porttype',
                                width: 8,
                                default: 'udp',
                                label: 'Port Type',
                                choices: [
                                        { id: 'tcp', label: 'TCP' },
                                        { id: 'udp', label: 'UDP' },
                                ],
                        },
                        {
                                type: 'dropdown',
                                id: 'protocol',
                                width: 8,
                                default: 'tsl3.1',
                                label: 'TSL Protcol Version',
                                choices: [
                                        { id: 'tsl3.1', label: 'TSL 3.1' },
                                        { id: 'tsl4.0', label: 'TSL 4.0' },
                                        { id: 'tsl5.0', label: 'TSL 5.0' },
                                        { id: 'rossvision', label: 'Ross Vision' },
                                ],
                        },
                        {
                                type: 'dropdown',
                                id: 'ross_main_mle',
                                width: 6,
                                default: 'mle1',
                                label: 'Main MLE',
                                tooltip: 'Select which MLE drives the tally output. Tally is only triggered for sources on this MLE or on secondary MLEs feeding into it.',
                                choices: [
                                        { id: 'mle1', label: 'MLE 1' },
                                        { id: 'mle2', label: 'MLE 2' },
                                        { id: 'mle3', label: 'MLE 3' },
                                ],
                                isVisible: (config) => config.protocol === 'rossvision',
                        },
                        {
                                type: 'number',
                                id: 'ross_mle1_addr',
                                width: 4,
                                default: 0,
                                label: 'MLE1 Source Address',
                                tooltip: 'The crosspoint address that represents MLE1 when it appears as a source on another MLE.',
                                min: 0,
                                max: 255,
                                isVisible: (config) => config.protocol === 'rossvision',
                        },
                        {
                                type: 'number',
                                id: 'ross_mle2_addr',
                                width: 4,
                                default: 0,
                                label: 'MLE2 Source Address',
                                tooltip: 'The crosspoint address that represents MLE2 when it appears as a source on another MLE.',
                                min: 0,
                                max: 255,
                                isVisible: (config) => config.protocol === 'rossvision',
                        },
                        {
                                type: 'number',
                                id: 'ross_mle3_addr',
                                width: 4,
                                default: 0,
                                label: 'MLE3 Source Address',
                                tooltip: 'The crosspoint address that represents MLE3 when it appears as a source on another MLE.',
                                min: 0,
                                max: 255,
                                isVisible: (config) => config.protocol === 'rossvision',
                        },
                        {
                                type: 'static-text',
                                id: 'dummy2',
                                width: 12,
                                label: ' ',
                                value: ' ',
                        },
                        {
                                type: 'textinput',
                                id: 'filter',
                                width: 6,
                                label: 'Label Filter',
                                tooltip: 'If the UMD label contains this text, remove it',
                                default: ' (FSFC)',
                        },
                        {
                                type: 'static-text',
                                id: 'dummy3',
                                width: 12,
                                label: ' ',
                                value: ' ',
                        },
                        {
                                type: 'checkbox',
                                id: 'verbose',
                                label: 'Enable Verbose Logging',
                                default: false,
                        },
                ]
        },
}
